---
Name: ecommerce-prepayment
After:
  - '#coreconfig'
---
Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig:
  extensions:
    - Sunnysideup\EcommercePrepayment\Extensions\PrepaymentConfigExtension
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\EcommercePrepayment\Extensions\PrepaymentMemberExtension
Sunnysideup\Ecommerce\Pages\Product:
  extensions:
    - Sunnysideup\EcommercePrepayment\Extensions\PrepaymentProductExtension
Sunnysideup\Ecommerce\Model\OrderItem:
  extensions:
    - Sunnysideup\EcommercePrepayment\Extensions\PrepaymentOrderItemExtension

Sunnysideup\Ecommerce\Cms\SalesAdmin:
  managed_models:
    - Sunnysideup\EcommercePrepayment\Model\PrepaymentHolder
